/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BookStoreManager;

import java.sql.Connection;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author honkaiwaifu
 */
public final class AdminPageForm extends javax.swing.JFrame {
    Connection con = NewConnection.getConnection();
    PreparedStatement ps;
    ResultSet rs;
    
    /**
     * Creates new form Main
     */
    public AdminPageForm() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem8 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        MainMenu = new javax.swing.JMenu();
        UserName = new javax.swing.JMenuItem();
        Changpassword = new javax.swing.JMenuItem();
        RecoveryKey = new javax.swing.JMenuItem();
        Logout = new javax.swing.JMenuItem();
        ExitApplication = new javax.swing.JMenuItem();
        BookInformationMenu = new javax.swing.JMenu();
        BookInformation = new javax.swing.JMenuItem();
        BookPublisher = new javax.swing.JMenuItem();
        CustomerInformation = new javax.swing.JMenuItem();
        DangerOption = new javax.swing.JCheckBoxMenuItem();
        EmployeeMenu = new javax.swing.JMenu();
        EmployeeInformation = new javax.swing.JMenuItem();
        GrantAccount = new javax.swing.JMenuItem();
        ReportMenu = new javax.swing.JMenu();
        BillHistory = new javax.swing.JMenuItem();
        DebitMonth = new javax.swing.JMenuItem();
        SalesMonth = new javax.swing.JMenuItem();
        AboutMenu = new javax.swing.JMenu();
        GroupInformation = new javax.swing.JMenuItem();

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN TRỊ HỆ THỐNG");
        jLabel2.setToolTipText("");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/1200px-El_Ateneo_Bookstore.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainMenu.setText("File");

        UserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8-name-16.png"))); // NOI18N
        UserName.setText("Thông tin tài khoản");
        MainMenu.add(UserName);

        Changpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/modify-key-icon (1).png"))); // NOI18N
        Changpassword.setText("Thay đổi mật khẩu");
        Changpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangpasswordActionPerformed(evt);
            }
        });
        MainMenu.add(Changpassword);

        RecoveryKey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/modify-key-icon (1).png"))); // NOI18N
        RecoveryKey.setText("Khoá phục hồi");
        RecoveryKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecoveryKeyActionPerformed(evt);
            }
        });
        MainMenu.add(RecoveryKey);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/Logout-icon.png"))); // NOI18N
        Logout.setText("Đăng xuất");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        MainMenu.add(Logout);

        ExitApplication.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        ExitApplication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/Actions-application-exit-icon.png"))); // NOI18N
        ExitApplication.setText("Thoát");
        ExitApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitApplicationActionPerformed(evt);
            }
        });
        MainMenu.add(ExitApplication);

        jMenuBar2.add(MainMenu);

        BookInformationMenu.setText("Thông tin");

        BookInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8-create-document-16.png"))); // NOI18N
        BookInformation.setText("Thông tin sách");
        BookInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookInformationActionPerformed(evt);
            }
        });
        BookInformationMenu.add(BookInformation);

        BookPublisher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8-create-document-16.png"))); // NOI18N
        BookPublisher.setText("Nhà xuất bản");
        BookPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookPublisherActionPerformed(evt);
            }
        });
        BookInformationMenu.add(BookPublisher);

        CustomerInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8-create-document-16.png"))); // NOI18N
        CustomerInformation.setText("Khách hàng");
        CustomerInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerInformationActionPerformed(evt);
            }
        });
        BookInformationMenu.add(CustomerInformation);

        DangerOption.setText("Cho phép xuất thông tin khách hàng");
        DangerOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangerOptionActionPerformed(evt);
            }
        });
        BookInformationMenu.add(DangerOption);

        jMenuBar2.add(BookInformationMenu);

        EmployeeMenu.setText("Nhân viên");

        EmployeeInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8-create-document-16.png"))); // NOI18N
        EmployeeInformation.setText("Thông tin nhân viên");
        EmployeeInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeInformationActionPerformed(evt);
            }
        });
        EmployeeMenu.add(EmployeeInformation);

        GrantAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8-create-document-16.png"))); // NOI18N
        GrantAccount.setText("Cấp tài khoản");
        GrantAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrantAccountActionPerformed(evt);
            }
        });
        EmployeeMenu.add(GrantAccount);

        jMenuBar2.add(EmployeeMenu);

        ReportMenu.setText("Báo cáo");

        BillHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8-create-document-16.png"))); // NOI18N
        BillHistory.setText("Lịch sử hoá đơn");
        BillHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillHistoryActionPerformed(evt);
            }
        });
        ReportMenu.add(BillHistory);

        DebitMonth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/Sales-report-icon.png"))); // NOI18N
        DebitMonth.setText("Công Nợ");
        DebitMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebitMonthActionPerformed(evt);
            }
        });
        ReportMenu.add(DebitMonth);

        SalesMonth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/Sales-report-icon.png"))); // NOI18N
        SalesMonth.setText("Doanh Thu");
        SalesMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesMonthActionPerformed(evt);
            }
        });
        ReportMenu.add(SalesMonth);

        jMenuBar2.add(ReportMenu);

        AboutMenu.setText("Về");
        AboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutMenuActionPerformed(evt);
            }
        });

        GroupInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8-info-16.png"))); // NOI18N
        GroupInformation.setText("Thông tin");
        GroupInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroupInformationActionPerformed(evt);
            }
        });
        AboutMenu.add(GroupInformation);

        jMenuBar2.add(AboutMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   //thoát pm
    private void ExitApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitApplicationActionPerformed
        // TODO add your handling code here:
        dispose();
        //ngắt kết nối với csdl khi thoát phần mềm
        try {
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(AdminPageForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_ExitApplicationActionPerformed
//đăng xuất
    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
         this.dispose();
         //ngắt kết nối với csdl khi đăng xuất
        try {
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(AdminPageForm.class.getName()).log(Level.SEVERE, null, ex);
        }
         LoginForm lf = new LoginForm();
         lf.setVisible(true);
         lf.setResizable(false);
         lf.pack();
         lf.setLocationRelativeTo(null);
         lf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         lf.setTitle("Đăng nhập hệ thống");
    }
//GEN-FIRST:event_LogoutActionPerformed

//GEN-LAST:event_LogoutActionPerformed
                                              
  //thay đổi mật khẩu
    private void ChangpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangpasswordActionPerformed
        // TODO add your handling code here:       
        ChangePassAdminAcc cp = new ChangePassAdminAcc();
        cp.setVisible(true);
        cp.setResizable(false);
        cp.pack();
        cp.setLocationRelativeTo(null);
        cp.setTitle("Thay đổi mật khẩu");
    }
//GEN-LAST:event_ChangpasswordActionPerformed
    //khoá phục hồi
    private void RecoveryKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecoveryKeyActionPerformed
        // TODO add your handling code here:
        RecAdminAcc rk = new RecAdminAcc();     
        rk.setVisible(true);
        rk.setResizable(false);
        rk.pack();
        rk.setLocationRelativeTo(null);
        rk.setTitle("Khoá phục hồi");
        
    }//GEN-LAST:event_RecoveryKeyActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:       
        //ngắt kết nối với csdl khi thoát phần mềm
        try {
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(AdminPageForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void GroupInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroupInformationActionPerformed
        // TODO add your handling code here:
        
        AboutSoftware as = new AboutSoftware();
        as.setVisible(true);
        as.setResizable(false);
        as.pack();
        as.setLocationRelativeTo(null);
        as.setTitle("Về phần mềm");
    }//GEN-LAST:event_GroupInformationActionPerformed

    private void AboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutMenuActionPerformed
    //Thông tin khách hàng
    private void CustomerInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerInformationActionPerformed
        // TODO add your handling code here:     
        CustomerInformation ci = new CustomerInformation();
        ci.setVisible(true);
        ci.setResizable(false);
        ci.pack();
        ci.setLocationRelativeTo(null);
        ci.setTitle("Thông tin khách hàng");
    }//GEN-LAST:event_CustomerInformationActionPerformed
    //Cấp tài khoản cho nhân viên
    private void GrantAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrantAccountActionPerformed
        // TODO add your handling code here:      
        GrantAccountForm ga = new GrantAccountForm();
        ga.setVisible(true);
        ga.setResizable(false);
        ga.pack();
        ga.setLocationRelativeTo(null);
        ga.setTitle("Cấp tài khoản nhân viên");
    }//GEN-LAST:event_GrantAccountActionPerformed
    //cho phep xuat thong tin khach hang
    private void DangerOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangerOptionActionPerformed
        // TODO add your handling code here:
        
        if (DangerOption.isSelected()){
            int asking0 = JOptionPane.showConfirmDialog(null, "Cho phép xuất thông tin khách hàng?\nĐây là dữ liệu nhạy cảm\n"
                    + "Kích hoạt đồng nghĩa chịu trách nhiệm nếu làm để lộ thông tin\nVẫn tiếp tục kích hoạt?",
                    "Cảnh báo",JOptionPane.YES_NO_OPTION,JOptionPane.ERROR_MESSAGE);
            if (asking0 == JOptionPane.YES_OPTION ) {               
                JOptionPane.showMessageDialog(null, "Kích hoạt thành công","Cảnh báo",JOptionPane.ERROR_MESSAGE);               
            } else if (asking0 == JOptionPane.NO_OPTION){
                this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            }
        } else {
             BookStoreManager.CustomerInformation.ExcelExport.setEnabled(false);
        }
    }//GEN-LAST:event_DangerOptionActionPerformed

    private void DebitMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebitMonthActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Tính năng chưa phát triển","Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_DebitMonthActionPerformed

    private void SalesMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesMonthActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Tính năng chưa phát triển","Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_SalesMonthActionPerformed
    //truy cập thông tin sách
    private void BookInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookInformationActionPerformed
        // TODO add your handling code here:
        BookInformation bookinfo = new BookInformation();
        bookinfo.setVisible(true);
        bookinfo.setResizable(false);
        bookinfo.pack();
        bookinfo.setLocationRelativeTo(null);
        bookinfo.setTitle("THÔNG TIN SÁCH");
    }//GEN-LAST:event_BookInformationActionPerformed
    //Thông tin NHÀ XUẤT BẢN
    private void BookPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookPublisherActionPerformed
        // TODO add your handling code here:
        BookPublishers bookpush = new BookPublishers();
        bookpush.setVisible(true);
        bookpush.setResizable(false);
        bookpush.pack();
        bookpush.setLocationRelativeTo(null);
        bookpush.setTitle("THÔNG TIN NHÀ XUẤT BẢN");
    }//GEN-LAST:event_BookPublisherActionPerformed
    //Thông tin nhân viên
    private void EmployeeInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeInformationActionPerformed
        // TODO add your handling code here:
        EmployeeInformation EmpInfo = new EmployeeInformation();
        EmpInfo.setVisible(true);
        EmpInfo.setResizable(false);
        EmpInfo.pack();
        EmpInfo.setLocationRelativeTo(null);
        EmpInfo.setTitle("THÔNG TIN NHÂN VIÊN");
    }//GEN-LAST:event_EmployeeInformationActionPerformed
    //Lịch sử hoá đơn
    private void BillHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillHistoryActionPerformed
        // TODO add your handling code here:
        BillHistory bhistory = new BillHistory();
        bhistory.setVisible(true);
        bhistory.setResizable(false);
        bhistory.pack();
        bhistory.setLocationRelativeTo(null);
        bhistory.setTitle("LỊCH SỬ HOÁ ĐƠN");
    }//GEN-LAST:event_BillHistoryActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                AdminPageForm mf = new AdminPageForm();
                mf.UserName.setEnabled(false);
                mf.setVisible(true);
                mf.setResizable(false);
                mf.setTitle("Quản lý đại lý");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AboutMenu;
    private javax.swing.JMenuItem BillHistory;
    private javax.swing.JMenuItem BookInformation;
    private javax.swing.JMenu BookInformationMenu;
    private javax.swing.JMenuItem BookPublisher;
    private javax.swing.JMenuItem Changpassword;
    private javax.swing.JMenuItem CustomerInformation;
    public static javax.swing.JCheckBoxMenuItem DangerOption;
    private javax.swing.JMenuItem DebitMonth;
    private javax.swing.JMenuItem EmployeeInformation;
    private javax.swing.JMenu EmployeeMenu;
    private javax.swing.JMenuItem ExitApplication;
    private javax.swing.JMenuItem GrantAccount;
    private javax.swing.JMenuItem GroupInformation;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenu MainMenu;
    private javax.swing.JMenuItem RecoveryKey;
    private javax.swing.JMenu ReportMenu;
    private javax.swing.JMenuItem SalesMonth;
    public static javax.swing.JMenuItem UserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
