/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BookStoreManager;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author honkaiwaifu
 */
public class ChangePassStorageAcc extends javax.swing.JFrame {

    Connection con = NewConnection.getConnection();
    /**
     * Creates new form ChangePassword
     */
    public ChangePassStorageAcc() {
        initComponents();
        StorageAccInfo.setText(StoragePageForm.StorageAcc.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newpassword = new javax.swing.JPasswordField();
        confirmpassword = new javax.swing.JPasswordField();
        ChangeButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        ShowPassword = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        oldpassword = new javax.swing.JPasswordField();
        StorageAccInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/Apps-password-icon.png"))); // NOI18N
        jLabel1.setText("Thay đổi mật khẩu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tài khoản hiện tại");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mật khẩu mới");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Xác nhận mật khẩu");

        newpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newpasswordKeyPressed(evt);
            }
        });

        confirmpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmpasswordKeyPressed(evt);
            }
        });

        ChangeButton.setText("Thay đổi");
        ChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Huỷ");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ShowPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ShowPassword.setText("Hiện mật khẩu");
        ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Mật khẩu cũ");

        oldpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                oldpasswordKeyPressed(evt);
            }
        });

        StorageAccInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StorageAccInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StorageAccInfo.setText("Tài khoản đang đăng nhập");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ShowPassword)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(63, 228, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(StorageAccInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(oldpassword)
                                    .addComponent(newpassword)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(186, 186, 186))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(14, 14, 14))
                                    .addComponent(confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(StorageAccInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oldpassword))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(newpassword)
                        .addGap(20, 20, 20)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmpassword))
                .addGap(20, 20, 20)
                .addComponent(ShowPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     
    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        int asking0 = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn thoát?","Thay dổi mật khẩu",JOptionPane.YES_NO_OPTION,JOptionPane.ERROR_MESSAGE);
        if (asking0 == JOptionPane.YES_OPTION ) {
            this.dispose();
           
            
        } else if (asking0 == JOptionPane.NO_OPTION){
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_CancelButtonActionPerformed
    //chức năng thay đổi mật khẩu
    private void ChangePassword_form() {
        String user, oldpass, newpass, confpass;
        user = StorageAccInfo.getText();
        oldpass = oldpassword.getText();
        newpass = newpassword.getText();
        confpass = confirmpassword.getText() ;
        
        
         if(oldpass.equals("")){
            JOptionPane.showMessageDialog(this,"Vui lòng nhập mật khẩu cũ!",
                    "Thay đổi mật khẩu",JOptionPane.ERROR_MESSAGE);   
        }
        else if(newpass.equals("")){
            JOptionPane.showMessageDialog(this,"Vui lòng nhập mật khẩu mới!",
                    "Thay đổi mật khẩu",JOptionPane.ERROR_MESSAGE);
        }  
        else if(confpass.equals("")){
            JOptionPane.showMessageDialog(this,"Vui lòng xác nhận mật khẩu mới!",
                    "Thay đổi mật khẩu",JOptionPane.ERROR_MESSAGE);
        }
            else {
            
            PreparedStatement ps , ps0;  
            ResultSet rs;
            try {
                ps = con.prepareStatement("SELECT * FROM DANGNHAP WHERE username = ?");
                ps.setString(1, user);
                ps0 = con.prepareStatement("UPDATE DANGNHAP SET password = ? WHERE username = ? ");
                ps0.setString(1, newpass);
                ps0.setString(2, user);
                rs = ps.executeQuery();              
                    if (rs.next() ) {
                        String getpassword = String.valueOf(rs.getString("password"));
                        if (BCrypt.checkpw( oldpass, getpassword)) {
                            if (newpass.equals(confpass)) { 
                                ps0.executeUpdate();
                                JOptionPane.showMessageDialog(null,"Thay đổi mật khẩu thành công!\nVui lòng đăng nhập lại!"
                                        + "\nSau khi đăng nhập lại, hãy xem mã phục hồi mới mà hệ thống đã tạo.",
                                    "",JOptionPane.INFORMATION_MESSAGE);
                                this.dispose();
                                new AdminPageForm().dispose();
                                LoginForm lf = new LoginForm();
                                lf.setVisible(true);
                                lf.setResizable(false);
                                lf.pack();
                                lf.setLocationRelativeTo(null);
                                lf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                            }
                            else if (!newpass.equals(confpass)) {
                                JOptionPane.showMessageDialog(null,"Mật khẩu mới không trùng khớp",
                                    "Thay đổi mật khẩu",JOptionPane.ERROR_MESSAGE);
                                newpassword.setText("");
                                confirmpassword.setText(""); 
                            } 
                        }  else {
                        JOptionPane.showMessageDialog(null,"Mật khẩu cũ không trùng khớp",
                            "Thay đổi mật khẩu",JOptionPane.ERROR_MESSAGE); 
                        oldpassword.setText("");
                        newpassword.setText("");
                        confirmpassword.setText(""); 
                    }
                }    
            } catch (SQLException ex) {
               java.util.logging.Logger.getLogger(ChangePassStorageAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }           
         } 
    }
    //nút thay đổi mật khẩu
    private void ChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeButtonActionPerformed
        // TODO add your handling code here:
       ChangePassword_form();
    }//GEN-LAST:event_ChangeButtonActionPerformed

    private void ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordActionPerformed
        // TODO add your handling code here:
          if (ShowPassword.isSelected()){
            oldpassword.setEchoChar((char)0);
            newpassword.setEchoChar((char)0);
            confirmpassword.setEchoChar((char)0);
        } else {
            oldpassword.setEchoChar('*');
            newpassword.setEchoChar('*');
            confirmpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowPasswordActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       new AdminPageForm().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void newpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newpasswordKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                if(newpassword.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Nhập mật khẩu mới trước!",
                "Thông báo",JOptionPane.ERROR_MESSAGE);
                } else {
                    confirmpassword.requestFocus();
                }
            }
    }//GEN-LAST:event_newpasswordKeyPressed
    
    private void confirmpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmpasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                ChangePassword_form();
            }
    }//GEN-LAST:event_confirmpasswordKeyPressed

    private void oldpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oldpasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldpasswordKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassStorageAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassStorageAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassStorageAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassStorageAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChangePassStorageAcc cp = new ChangePassStorageAcc();
                cp.setVisible(true);
                cp.setResizable(false);
                cp.setTitle("Thay đổi mật khẩu");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton ChangeButton;
    private javax.swing.JCheckBox ShowPassword;
    private javax.swing.JLabel StorageAccInfo;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField newpassword;
    private javax.swing.JPasswordField oldpassword;
    // End of variables declaration//GEN-END:variables
}
