/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BookStoreManager;

import java.sql.Connection;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author honkaiwaifu
 */
public final class SalerPageForm extends javax.swing.JFrame {
    Connection con = NewConnection.getConnection();
    PreparedStatement ps;
    ResultSet rs;
    
    /**
     * Creates new form Main
     */
    public SalerPageForm() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem8 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        SalerAcc = new javax.swing.JMenuItem();
        Changpassword = new javax.swing.JMenuItem();
        RecoveryKey = new javax.swing.JMenuItem();
        Logout = new javax.swing.JMenuItem();
        ExitApplication = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        BillPay = new javax.swing.JMenuItem();
        BillHistory = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NHÂN VIÊN BÁN HÀNG");
        jLabel2.setToolTipText("");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/1200px-El_Ateneo_Bookstore.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("File");

        SalerAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8-name-16.png"))); // NOI18N
        SalerAcc.setText("Thông tin tài khoản");
        jMenu1.add(SalerAcc);

        Changpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/modify-key-icon (1).png"))); // NOI18N
        Changpassword.setText("Thay đổi mật khẩu");
        Changpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangpasswordActionPerformed(evt);
            }
        });
        jMenu1.add(Changpassword);

        RecoveryKey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/modify-key-icon (1).png"))); // NOI18N
        RecoveryKey.setText("Khoá phục hồi");
        RecoveryKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecoveryKeyActionPerformed(evt);
            }
        });
        jMenu1.add(RecoveryKey);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/Logout-icon.png"))); // NOI18N
        Logout.setText("Đăng xuất");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jMenu1.add(Logout);

        ExitApplication.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        ExitApplication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/Actions-application-exit-icon.png"))); // NOI18N
        ExitApplication.setText("Thoát");
        ExitApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitApplicationActionPerformed(evt);
            }
        });
        jMenu1.add(ExitApplication);

        jMenuBar2.add(jMenu1);

        jMenu3.setText("Nhân viên");

        BillPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8-package-16.png"))); // NOI18N
        BillPay.setText("Thanh toán ");
        BillPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillPayActionPerformed(evt);
            }
        });
        jMenu3.add(BillPay);

        BillHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8-create-document-16.png"))); // NOI18N
        BillHistory.setText("Lịch sử hoá đơn");
        BillHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillHistoryActionPerformed(evt);
            }
        });
        jMenu3.add(BillHistory);

        jMenuBar2.add(jMenu3);

        jMenu6.setText("Về");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8-info-16.png"))); // NOI18N
        jMenuItem7.setText("Thông tin");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   //thoát pm
    private void ExitApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitApplicationActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_ExitApplicationActionPerformed
//đăng xuất
    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
         this.dispose();
         LoginForm lf = new LoginForm();
         lf.setVisible(true);
         lf.setResizable(false);
         lf.pack();
         lf.setLocationRelativeTo(null);
         lf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         lf.setTitle("Đăng nhập hệ thống");
    }
//GEN-FIRST:event_LogoutActionPerformed

//GEN-LAST:event_LogoutActionPerformed
                                              
  //thay đổi mật khẩu
    private void ChangpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangpasswordActionPerformed
        // TODO add your handling code here:
        ChangePassSalerAcc cp = new ChangePassSalerAcc();
        cp.setVisible(true);
        cp.setResizable(false);
        cp.pack();
        cp.setLocationRelativeTo(null);
        cp.setTitle("Thay đổi mật khẩu");
    }
//GEN-LAST:event_ChangpasswordActionPerformed
    //khoá phục hồi
    private void RecoveryKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecoveryKeyActionPerformed
        // TODO add your handling code here:
        RecAdminAcc rk = new RecAdminAcc();
       
        rk.setVisible(true);
        rk.setResizable(false);
        rk.pack();
        rk.setLocationRelativeTo(null);
        rk.setTitle("Khoá phục hồi");
        try {
            ps = con.prepareStatement("SELECT * FROM DANGNHAP WHERE username = ?");
            ps.setString(1, SalerAcc.getText());
            rs = ps.executeQuery();
            if (rs.next()) {
                 rk.username.setText(rs.getString(2));
                }
            con.close();
            } 
            catch (SQLException ex) {
                java.util.logging.Logger.getLogger(SalerPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_RecoveryKeyActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        
        AboutSoftware as = new AboutSoftware();
        as.setVisible(true);
        as.setResizable(false);
        as.pack();
        as.setLocationRelativeTo(null);
        as.setTitle("Về chúng tôi");
    }//GEN-LAST:event_jMenuItem7ActionPerformed
    //Lịch sử hoá đơn
    private void BillHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillHistoryActionPerformed
        // TODO add your handling code here:
        BillHistory bhistory = new BillHistory();
        bhistory.setVisible(true);
        bhistory.setResizable(false);
        bhistory.pack();
        bhistory.setLocationRelativeTo(null);
        bhistory.setTitle("LỊCH SỬ HOÁ ĐƠN");
    }//GEN-LAST:event_BillHistoryActionPerformed
    //thanh toán
    private void BillPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillPayActionPerformed
        // TODO add your handling code here:
        SalerForm sf = new SalerForm();
        sf.setVisible(true);
        sf.setResizable(false);
        sf.pack();
        sf.setLocationRelativeTo(null);
        sf.setTitle("THANH TOÁN");
    }//GEN-LAST:event_BillPayActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalerPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalerPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalerPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalerPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                SalerPageForm mf = new SalerPageForm();
                SalerPageForm.SalerAcc.setEnabled(false);
                mf.setVisible(true);
                mf.setResizable(false);
                mf.setTitle("Quản lý đại lý");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BillHistory;
    private javax.swing.JMenuItem BillPay;
    private javax.swing.JMenuItem Changpassword;
    private javax.swing.JMenuItem ExitApplication;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenuItem RecoveryKey;
    public static javax.swing.JMenuItem SalerAcc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
